services:
  - type: web
    name: communityfix-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
